Bump Prowlarr image from 0.4.5-nightly to latest
IceWhaleTech/CasaOS-AppStore pull request #151
Opened 2023-05-15 00:23 UTC by charagender

Prowlarr image was really old as mentioned in Issue #19 so this updates it to use the latest image available

2023-05-15 00:30 UTC, charagender commented
After going through more apps, I noticed a lot of them are static versions and would have to be updated manually by going into their `docker-compose.yml` files and bumping their versions. Should they be updated to use `latest` instead?

2023-05-16 07:36 UTC, tigerinus requested changes

2023-05-16 07:36 UTC, tigerinus commented on Apps/Prowlarr/docker-compose.yml
> +    image: lscr.io/linuxserver/prowlarr:latest
Please use specific tag instead of `latest`. Using `latest` adds version uncertainty.

2023-05-16 17:59 UTC, tigerinus commented
@charagender I am so happy that you took the action and take over updating app tags! Huge thanks!

There is just one issue about all major version changes. Please see my comments in the code.

2023-05-16 17:59 UTC, tigerinus requested changes

2023-05-16 17:59 UTC, tigerinus commented on Apps/2FAuth/docker-compose.yml
> +    image: 2fauth/2fauth:4.0.2
That's a change in major version. Have you tested this version against existing configurations in the compose yaml (i.e. env, memory, etc.)?

If not, it's simpler to just update its minor/build version for now.

2023-05-16 17:59 UTC, tigerinus commented on Apps/Grafana/docker-compose.yml
> +    image: grafana/grafana:9.5.2
See the comments about major version change above.

2023-05-16 17:59 UTC, tigerinus commented on Apps/Nextcloud/docker-compose.yml
> +    image: nextcloud:26.0.1
See the comments about major version change above.

2023-05-16 17:59 UTC, tigerinus commented on Apps/Node-RED/docker-compose.yml
> +    image: nodered/node-red:3.0.2-18
See the comments about major version change above.

2023-05-16 17:59 UTC, tigerinus commented on Apps/Prowlarr/docker-compose.yml
> +    image: lscr.io/linuxserver/prowlarr:1.4.1
See the comments about major version change above.

2023-05-16 17:59 UTC, tigerinus commented on Apps/Sabnzbd/docker-compose.yml
> +    image: linuxserver/sabnzbd:4.0.1
See the comments about major version change above.

2023-05-16 17:59 UTC, tigerinus commented on Apps/Transmission/docker-compose.yml
> +    image: lscr.io/linuxserver/transmission:4.0.3
See the comments about major version change above.

2023-05-16 18:01 UTC, charagender commented
> @charagender I am so happy that you took the action and take over updating app tags! Huge thanks!
> 
> There is just one issue about all major version changes. Please see my comments in the code.

That's what I was about to do actually! That's why I hadn't yet done a request for comment. I'm just trying to install Debian on my computer now to test all the changes, because I don't have a way of controlling the computer I have CasaOS installed on anymore

2023-05-25 02:41 UTC, charagender commented
@tigerinus yes! it's just that I haven't had much time to dedicate to things other than studying recently because of uni exams, though I think I'll have time to test things this weekend

2023-06-11 13:54 UTC, tigerinus commented
This work is mostly covered in https://github.com/IceWhaleTech/CasaOS-AppStore/pull/176

Thanks again @charagender for starting it. Looking forward to more contributions from you!

2023-06-11 13:54 UTC, closed without merging

2023-06-11 14:50 UTC, charagender commented
alright, thank you! I hope I'm able to! turns out uni is harder than I thought, so that's my priority right now