[New Apps] MotionEye
IceWhaleTech/CasaOS-AppStore pull request #247
Opened 2023-08-09 07:44 UTC by f4bio

This PR adds 

⭐ [motion-eye](https://github.com/motioneye-project/motioneye) Version 0.42.1 (aka `master-amd64`; aka `stable`)

2023-08-11 03:40 UTC, raller1028 commented
@f4bio  need help@ @, I used your docker-compose.yml file to import it, and the app won't start.
![image](https://github.com/IceWhaleTech/CasaOS-AppStore/assets/57336867/b8f75da8-7957-418e-88a9-a84d97a232cd)

2023-08-11 07:11 UTC, f4bio commented
I just pushed an update, can you test again?

-
thanks for your help!

2023-08-17 20:53 UTC, tigerinus requested changes

2023-08-17 20:53 UTC, tigerinus commented on Apps/Motioneye/docker-compose.yml
> +    devices: []
Please remove properties with empty list. There's a known issue that this will break the AppStore.

2023-08-17 20:53 UTC, tigerinus commented on Apps/Motioneye/docker-compose.yml
> +    cap_add: []
Please remove properties with empty list. There's a known issue that this will break the AppStore.

2023-08-17 20:53 UTC, tigerinus commented on Apps/Motioneye/docker-compose.yml
> +    command: []
Please remove properties with empty list. There's a known issue that this will break the AppStore.

2023-08-17 20:53 UTC, tigerinus commented on Apps/Motioneye/docker-compose.yml
> +    custom: ""
There's no need to include a property if its value is an empty string

2023-08-17 20:53 UTC, tigerinus commented on Apps/Motioneye/docker-compose.yml
> +  hostname: ""
There's no need to include a property if its value is an empty string

2023-10-20 03:22 UTC, f4bio commented
Sorry for the late response! 
thanks so much @tigerinus for your input!

2023-10-20 06:17 UTC, tigerinus approved these changes

2023-11-02 09:41 UTC, raller1028 commented
Sorry for the late validation of your pull request, thanks for your submitting it.

2023-11-02 09:41 UTC, merged