update compose
IceWhaleTech/CasaOS-AppStore pull request #648
Opened 2024-12-23 10:53 UTC by LinkLeong

2024-12-23 10:57 UTC, LinkLeong commented
#645

2024-12-24 06:41 UTC, CorrectRoadH commented
这里请写版本号，不要latest

2025-03-15 13:28 UTC, Cadavanaugh commented
According to the contribution documentation we should not use `latest` tag for `image`.
[CONTRIBUTING.md](https://github.com/IceWhaleTech/CasaOS-AppStore/blob/main/CONTRIBUTING.md)
[What's wrong with latest tag?](https://github.com/IceWhaleTech/CasaOS-AppStore/issues/167)

2025-03-15 13:30 UTC, Cadavanaugh requested changes
According to the contribution documentation we should not use latest tag for image.
[CONTRIBUTING.md](https://github.com/IceWhaleTech/CasaOS-AppStore/blob/main/CONTRIBUTING.md)
[What's wrong with latest tag?](https://github.com/IceWhaleTech/CasaOS-AppStore/issues/167)

2025-03-15 13:30 UTC, Cadavanaugh commented on Apps/AnythingLLM/docker-compose.yml
> +    image: mintplexlabs/anythingllm:latest
According to the contribution documentation we should not use latest tag for image.
[CONTRIBUTING.md](https://github.com/IceWhaleTech/CasaOS-AppStore/blob/main/CONTRIBUTING.md)
[What's wrong with latest tag?](https://github.com/IceWhaleTech/CasaOS-AppStore/issues/167)

2025-03-20 08:32 UTC, closed without merging